# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/api/iris_processed.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='internal/api/iris_processed.proto',
  package='',
  syntax='proto3',
  serialized_options=b'Z\014internal/api',
  serialized_pb=b'\n!internal/api/iris_processed.proto\"\x93\x01\n\rProcessedData\x12\x0c\n\x04size\x18\x01 \x01(\x01\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x13\n\x0bpetalLength\x18\x03 \x03(\x01\x12\x12\n\npetalWidth\x18\x04 \x03(\x01\x12\x13\n\x0bsepalLength\x18\x05 \x03(\x01\x12\x12\n\nsepalWidth\x18\x06 \x03(\x01\x12\x0f\n\x07species\x18\x07 \x03(\x01\x42\x0eZ\x0cinternal/apib\x06proto3'
)




_PROCESSEDDATA = _descriptor.Descriptor(
  name='ProcessedData',
  full_name='ProcessedData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='size', full_name='ProcessedData.size', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='ProcessedData.timestamp', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='petalLength', full_name='ProcessedData.petalLength', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='petalWidth', full_name='ProcessedData.petalWidth', index=3,
      number=4, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sepalLength', full_name='ProcessedData.sepalLength', index=4,
      number=5, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sepalWidth', full_name='ProcessedData.sepalWidth', index=5,
      number=6, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='species', full_name='ProcessedData.species', index=6,
      number=7, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=185,
)

DESCRIPTOR.message_types_by_name['ProcessedData'] = _PROCESSEDDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProcessedData = _reflection.GeneratedProtocolMessageType('ProcessedData', (_message.Message,), {
  'DESCRIPTOR' : _PROCESSEDDATA,
  '__module__' : 'internal.api.iris_processed_pb2'
  # @@protoc_insertion_point(class_scope:ProcessedData)
  })
_sym_db.RegisterMessage(ProcessedData)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
