// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.11.4
// source: internal/api/iris_interim.proto

package api

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type InterimData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Records []*InterimData_Record `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
}

func (x *InterimData) Reset() {
	*x = InterimData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_iris_interim_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InterimData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterimData) ProtoMessage() {}

func (x *InterimData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_iris_interim_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterimData.ProtoReflect.Descriptor instead.
func (*InterimData) Descriptor() ([]byte, []int) {
	return file_internal_api_iris_interim_proto_rawDescGZIP(), []int{0}
}

func (x *InterimData) GetRecords() []*InterimData_Record {
	if x != nil {
		return x.Records
	}
	return nil
}

type InterimData_Record struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SepalLength float64 `protobuf:"fixed64,1,opt,name=SepalLength,proto3" json:"SepalLength,omitempty"`
	SepalWidth  float64 `protobuf:"fixed64,2,opt,name=SepalWidth,proto3" json:"SepalWidth,omitempty"`
	PetalLength float64 `protobuf:"fixed64,3,opt,name=PetalLength,proto3" json:"PetalLength,omitempty"`
	PetalWidth  float64 `protobuf:"fixed64,4,opt,name=PetalWidth,proto3" json:"PetalWidth,omitempty"`
	Species     string  `protobuf:"bytes,5,opt,name=Species,proto3" json:"Species,omitempty"`
}

func (x *InterimData_Record) Reset() {
	*x = InterimData_Record{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_iris_interim_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InterimData_Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterimData_Record) ProtoMessage() {}

func (x *InterimData_Record) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_iris_interim_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterimData_Record.ProtoReflect.Descriptor instead.
func (*InterimData_Record) Descriptor() ([]byte, []int) {
	return file_internal_api_iris_interim_proto_rawDescGZIP(), []int{0, 0}
}

func (x *InterimData_Record) GetSepalLength() float64 {
	if x != nil {
		return x.SepalLength
	}
	return 0
}

func (x *InterimData_Record) GetSepalWidth() float64 {
	if x != nil {
		return x.SepalWidth
	}
	return 0
}

func (x *InterimData_Record) GetPetalLength() float64 {
	if x != nil {
		return x.PetalLength
	}
	return 0
}

func (x *InterimData_Record) GetPetalWidth() float64 {
	if x != nil {
		return x.PetalWidth
	}
	return 0
}

func (x *InterimData_Record) GetSpecies() string {
	if x != nil {
		return x.Species
	}
	return ""
}

var File_internal_api_iris_interim_proto protoreflect.FileDescriptor

var file_internal_api_iris_interim_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x69,
	0x72, 0x69, 0x73, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x69, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xe5, 0x01, 0x0a, 0x0b, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x69, 0x6d, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x2d, 0x0a, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x69, 0x6d, 0x44, 0x61, 0x74, 0x61,
	0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73,
	0x1a, 0xa6, 0x01, 0x0a, 0x06, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x53,
	0x65, 0x70, 0x61, 0x6c, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x0b, 0x53, 0x65, 0x70, 0x61, 0x6c, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x1e, 0x0a,
	0x0a, 0x53, 0x65, 0x70, 0x61, 0x6c, 0x57, 0x69, 0x64, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x0a, 0x53, 0x65, 0x70, 0x61, 0x6c, 0x57, 0x69, 0x64, 0x74, 0x68, 0x12, 0x20, 0x0a,
	0x0b, 0x50, 0x65, 0x74, 0x61, 0x6c, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x0b, 0x50, 0x65, 0x74, 0x61, 0x6c, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12,
	0x1e, 0x0a, 0x0a, 0x50, 0x65, 0x74, 0x61, 0x6c, 0x57, 0x69, 0x64, 0x74, 0x68, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x0a, 0x50, 0x65, 0x74, 0x61, 0x6c, 0x57, 0x69, 0x64, 0x74, 0x68, 0x12,
	0x18, 0x0a, 0x07, 0x53, 0x70, 0x65, 0x63, 0x69, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x53, 0x70, 0x65, 0x63, 0x69, 0x65, 0x73, 0x42, 0x0e, 0x5a, 0x0c, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_internal_api_iris_interim_proto_rawDescOnce sync.Once
	file_internal_api_iris_interim_proto_rawDescData = file_internal_api_iris_interim_proto_rawDesc
)

func file_internal_api_iris_interim_proto_rawDescGZIP() []byte {
	file_internal_api_iris_interim_proto_rawDescOnce.Do(func() {
		file_internal_api_iris_interim_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_api_iris_interim_proto_rawDescData)
	})
	return file_internal_api_iris_interim_proto_rawDescData
}

var file_internal_api_iris_interim_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_api_iris_interim_proto_goTypes = []interface{}{
	(*InterimData)(nil),        // 0: InterimData
	(*InterimData_Record)(nil), // 1: InterimData.Record
}
var file_internal_api_iris_interim_proto_depIdxs = []int32{
	1, // 0: InterimData.records:type_name -> InterimData.Record
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_api_iris_interim_proto_init() }
func file_internal_api_iris_interim_proto_init() {
	if File_internal_api_iris_interim_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_api_iris_interim_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InterimData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_iris_interim_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InterimData_Record); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_api_iris_interim_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_api_iris_interim_proto_goTypes,
		DependencyIndexes: file_internal_api_iris_interim_proto_depIdxs,
		MessageInfos:      file_internal_api_iris_interim_proto_msgTypes,
	}.Build()
	File_internal_api_iris_interim_proto = out.File
	file_internal_api_iris_interim_proto_rawDesc = nil
	file_internal_api_iris_interim_proto_goTypes = nil
	file_internal_api_iris_interim_proto_depIdxs = nil
}
