// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.11.4
// source: internal/api/iris_processed.proto

package api

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ProcessedData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Size        float64   `protobuf:"fixed64,1,opt,name=size,proto3" json:"size,omitempty"`
	Timestamp   int64     `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	PetalLength []float64 `protobuf:"fixed64,3,rep,packed,name=petalLength,proto3" json:"petalLength,omitempty"`
	PetalWidth  []float64 `protobuf:"fixed64,4,rep,packed,name=petalWidth,proto3" json:"petalWidth,omitempty"`
	SepalLength []float64 `protobuf:"fixed64,5,rep,packed,name=sepalLength,proto3" json:"sepalLength,omitempty"`
	SepalWidth  []float64 `protobuf:"fixed64,6,rep,packed,name=sepalWidth,proto3" json:"sepalWidth,omitempty"`
	Species     []float64 `protobuf:"fixed64,7,rep,packed,name=species,proto3" json:"species,omitempty"`
}

func (x *ProcessedData) Reset() {
	*x = ProcessedData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_iris_processed_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessedData) ProtoMessage() {}

func (x *ProcessedData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_iris_processed_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessedData.ProtoReflect.Descriptor instead.
func (*ProcessedData) Descriptor() ([]byte, []int) {
	return file_internal_api_iris_processed_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessedData) GetSize() float64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ProcessedData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ProcessedData) GetPetalLength() []float64 {
	if x != nil {
		return x.PetalLength
	}
	return nil
}

func (x *ProcessedData) GetPetalWidth() []float64 {
	if x != nil {
		return x.PetalWidth
	}
	return nil
}

func (x *ProcessedData) GetSepalLength() []float64 {
	if x != nil {
		return x.SepalLength
	}
	return nil
}

func (x *ProcessedData) GetSepalWidth() []float64 {
	if x != nil {
		return x.SepalWidth
	}
	return nil
}

func (x *ProcessedData) GetSpecies() []float64 {
	if x != nil {
		return x.Species
	}
	return nil
}

var File_internal_api_iris_processed_proto protoreflect.FileDescriptor

var file_internal_api_iris_processed_proto_rawDesc = []byte{
	0x0a, 0x21, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x69,
	0x72, 0x69, 0x73, 0x5f, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xdf, 0x01, 0x0a, 0x0d, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65,
	0x64, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x65, 0x74, 0x61, 0x6c,
	0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x03, 0x20, 0x03, 0x28, 0x01, 0x52, 0x0b, 0x70, 0x65,
	0x74, 0x61, 0x6c, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x65, 0x74,
	0x61, 0x6c, 0x57, 0x69, 0x64, 0x74, 0x68, 0x18, 0x04, 0x20, 0x03, 0x28, 0x01, 0x52, 0x0a, 0x70,
	0x65, 0x74, 0x61, 0x6c, 0x57, 0x69, 0x64, 0x74, 0x68, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x65, 0x70,
	0x61, 0x6c, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x05, 0x20, 0x03, 0x28, 0x01, 0x52, 0x0b,
	0x73, 0x65, 0x70, 0x61, 0x6c, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x1e, 0x0a, 0x0a, 0x73,
	0x65, 0x70, 0x61, 0x6c, 0x57, 0x69, 0x64, 0x74, 0x68, 0x18, 0x06, 0x20, 0x03, 0x28, 0x01, 0x52,
	0x0a, 0x73, 0x65, 0x70, 0x61, 0x6c, 0x57, 0x69, 0x64, 0x74, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x70, 0x65, 0x63, 0x69, 0x65, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x01, 0x52, 0x07, 0x73, 0x70,
	0x65, 0x63, 0x69, 0x65, 0x73, 0x42, 0x0e, 0x5a, 0x0c, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_api_iris_processed_proto_rawDescOnce sync.Once
	file_internal_api_iris_processed_proto_rawDescData = file_internal_api_iris_processed_proto_rawDesc
)

func file_internal_api_iris_processed_proto_rawDescGZIP() []byte {
	file_internal_api_iris_processed_proto_rawDescOnce.Do(func() {
		file_internal_api_iris_processed_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_api_iris_processed_proto_rawDescData)
	})
	return file_internal_api_iris_processed_proto_rawDescData
}

var file_internal_api_iris_processed_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_api_iris_processed_proto_goTypes = []interface{}{
	(*ProcessedData)(nil), // 0: ProcessedData
}
var file_internal_api_iris_processed_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_api_iris_processed_proto_init() }
func file_internal_api_iris_processed_proto_init() {
	if File_internal_api_iris_processed_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_api_iris_processed_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessedData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_api_iris_processed_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_api_iris_processed_proto_goTypes,
		DependencyIndexes: file_internal_api_iris_processed_proto_depIdxs,
		MessageInfos:      file_internal_api_iris_processed_proto_msgTypes,
	}.Build()
	File_internal_api_iris_processed_proto = out.File
	file_internal_api_iris_processed_proto_rawDesc = nil
	file_internal_api_iris_processed_proto_goTypes = nil
	file_internal_api_iris_processed_proto_depIdxs = nil
}
