# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/api/iris_interim.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='internal/api/iris_interim.proto',
  package='',
  syntax='proto3',
  serialized_options=b'Z\014internal/api',
  serialized_pb=b'\n\x1finternal/api/iris_interim.proto\"\xa0\x01\n\x0bInterimData\x12$\n\x07records\x18\x01 \x03(\x0b\x32\x13.InterimData.Record\x1ak\n\x06Record\x12\x13\n\x0bSepalLength\x18\x01 \x01(\x01\x12\x12\n\nSepalWidth\x18\x02 \x01(\x01\x12\x13\n\x0bPetalLength\x18\x03 \x01(\x01\x12\x12\n\nPetalWidth\x18\x04 \x01(\x01\x12\x0f\n\x07Species\x18\x05 \x01(\tB\x0eZ\x0cinternal/apib\x06proto3'
)




_INTERIMDATA_RECORD = _descriptor.Descriptor(
  name='Record',
  full_name='InterimData.Record',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='SepalLength', full_name='InterimData.Record.SepalLength', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='SepalWidth', full_name='InterimData.Record.SepalWidth', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='PetalLength', full_name='InterimData.Record.PetalLength', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='PetalWidth', full_name='InterimData.Record.PetalWidth', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Species', full_name='InterimData.Record.Species', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=196,
)

_INTERIMDATA = _descriptor.Descriptor(
  name='InterimData',
  full_name='InterimData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='records', full_name='InterimData.records', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_INTERIMDATA_RECORD, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=196,
)

_INTERIMDATA_RECORD.containing_type = _INTERIMDATA
_INTERIMDATA.fields_by_name['records'].message_type = _INTERIMDATA_RECORD
DESCRIPTOR.message_types_by_name['InterimData'] = _INTERIMDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InterimData = _reflection.GeneratedProtocolMessageType('InterimData', (_message.Message,), {

  'Record' : _reflection.GeneratedProtocolMessageType('Record', (_message.Message,), {
    'DESCRIPTOR' : _INTERIMDATA_RECORD,
    '__module__' : 'internal.api.iris_interim_pb2'
    # @@protoc_insertion_point(class_scope:InterimData.Record)
    })
  ,
  'DESCRIPTOR' : _INTERIMDATA,
  '__module__' : 'internal.api.iris_interim_pb2'
  # @@protoc_insertion_point(class_scope:InterimData)
  })
_sym_db.RegisterMessage(InterimData)
_sym_db.RegisterMessage(InterimData.Record)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
